name: ternacious
channels:
  - defaults
dependencies:
  - pip=25.1
  - python=3.11.13
  - pip:
    - openmeteo-requests==1.5.0
    - openmeteo-sdk==1.20.1
    - pandas==2.3.0
    - requests==2.32.3
    - retry-requests==2.0.0
    - selenium==4.33.0
